### ISSUE TITLE
sqlite.c?

### ISSUE THREAD

**Issue by robertmryan** [chrismsimpson/SwiftSQLite#2]
I notice that you're bridging to C functions for `sqlite3_bind_text` and `sqlite3_bind_blob`. I'm not sure why you did that, but that's entirely unnecessary. You can call those functions from Swift, just like you do with all of the other SQLite functions. The only trick, in my opinion, is that `SQLITE_TRANSIENT` isn't defined in Swift, but you can refer to http://stackoverflow.com/a/26884081/1271826 for example of how to define that natively in Swift:

    let SQLITE_STATIC = sqlite3_destructor_type(COpaquePointer(bitPattern: 0))
    let SQLITE_TRANSIENT = sqlite3_destructor_type(COpaquePointer(bitPattern: -1))

**Comment by chrismsimpson** [comment]
This didn't work in Swift 1.0 beta, for whatever reason (can't remember what exactly). I've just had a look, and your suggestion works, so I'll remove the sqlite.c.
